#!/usr/bin/env bash
# Bash (init) script that manages `manage_my_process`

# When passing the argument `start`:
#+ Starts 'manage_my_process'
#+ Creates a file containing its PID in '/var/run/my_process.pid'
#+ Displays 'manage_my_process started'

# When passing the argument `stop`:
#+ Stops 'manage_my_process'
#+ Deletes the file '/var/run/my_process.pid'
#+ Displays 'manage_my_process stopped'

# When passing the argument 'restart'
#+ Stops 'manage_my_process'
#+ Deletes the file '/var/run/my_process.pid'
#+ Starts 'manage_my_process'
#+ Creates a file containing its PID in '/var/run/my_process.pid'
#+ Displays 'manage_my_process restarted'

# Displays 'Usage: manage_my_process {start|stop|restart}'
#+ if any other argument or no argument is passed


mypidfile="/var/run/my_process.pid"

function start() {
	./manage_my_process &
	sudo touch "$mypidfile";
        sudo chown "$USER":"$USER" "$mypidfile";
        echo "$!" > "$mypidfile";
}

function stop() {
	kill "$(cat "$mypidfile")"
	sudo rm "$mypidfile"
}

if [ "$1" == "start" ]
then
	start
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
	stop
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	stop && start
	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
