#!/usr/bin/env bash
# Bash script that displays `To infinity and beyond` indefinitely
# In between each iteration of the loop, add a `sleep 2`

while 'true'
do
	printf "To infinity and beyond\n"

	sleep 2
done
