#!/usr/bin/env bash
# Bash script that stops `4-to_infinity_and_beyond` process
# You cannot use `kill` or `killall`

pid=$(pgrep -f 4-to_infinity_and_beyond)

if [ "$pid" -gt 0 ]
then
	pkill -f 4-to_infinity_and_beyond
fi
