#!/usr/bin/env bash
# script that displays the content of the file '/etc/passwd'
# Using the value of each field of a line to construct a sentence

FILE=/etc/passwd

lines=0

IFS=':'

lines="$(wc -l < $FILE)"

fields=('USERNAME' 'PASSWORD' 'USERID' 'GROUPID' 'USERIDINFO' 'HOMEDIR' 'SHELL')

i=1

while [[ $i -le $lines ]]
do
    	read -r -a fields < <(tail -n 1 <(head -n $i < $FILE))
    	echo -n "The user ${fields[0]} is part of the ${fields[3]} gang, lives in ${fields[5]} and "
	echo -n "rides ${fields[6]}. ${fields[2]}'s place is protected by the passcode ${fields[1]}, more "
	echo "info about the user here: ${fields[4]}"
	(( i++ ))
done
