#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes using a 'while' loop
# display hours from 0 to 12
# display minutes from 1 to 59


(( hour = 0 ))


while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"

	(( minute = 1 ))

	while [ "$minute" -le 59 ]
	do
		echo "$minute"

		(( sec = 1 ))

		while [ "$sec" -le 60 ]
		do
			(( sec++ ))
		done

		(( minute++ ))
	done

	(( hour++ ))
done
